
  - name: Install Docker prerequisites
    become: yes
    apt:     
        name: "{{packages}}"
        state: present
        update_cache: yes
    vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

  - name: Add Docker GPG key
    become: yes
    apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
  - name: Add Docker APT repository
    become: yes
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
      state: present
      filename: docker-ce
  - name: Install Docker
    become: yes
    apt:
        name: docker-ce
        update_cache: yes