- name: add syncthing ppa key
  become: yes
  apt_key:
    url:   https://syncthing.net/release-key.txt
    state: present
- name: add syncthing repo
  become: yes
  apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present
    filename: syncthing
- name: install syncthing
  become: yes
  apt:
    name: syncthing
    update_cache: yes
- name: prepare autostart dir
  file:
    path: ~/.config/autostart
    state: directory
- name: symlink syncthing desktop entry
  file:
    src: /usr/share/applications/syncthing-start.desktop
    dest: ~/.config/autostart/syncthing.desktop
    state: link
    force: yes
